# Generated by Django 4.2 on 2023-05-25 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0002_delete_infos_delete_userlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientid', models.CharField(max_length=255)),
                ('cname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='companydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyid', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='markettime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeid', models.CharField(max_length=255)),
                ('mtime', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operatorid', models.CharField(max_length=255)),
                ('operatorname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleid', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='marketdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oem', models.CharField(max_length=255, null=True)),
                ('marketname', models.CharField(max_length=255)),
                ('Specific_Market_Guidline', models.CharField(max_length=255)),
                ('Ciq', models.FileField(null=True, upload_to='marketdata')),
                ('Call_test_info', models.FileField(null=True, upload_to='marketdata')),
                ('Call_test_files', models.FileField(null=True, upload_to='marketdata')),
                ('Site_access', models.FileField(null=True, upload_to='marketdata')),
                ('Guidelines', models.FileField(null=True, upload_to='marketdata')),
                ('additional_Guidelines', models.FileField(null=True, upload_to='marketdata')),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.clientname')),
                ('operatorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.operator')),
                ('timeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.markettime')),
            ],
        ),
        migrations.CreateModel(
            name='infos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('secondname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('password', models.CharField(max_length=255)),
                ('companyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.companydata')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userlist')),
            ],
        ),
    ]
