# Generated by Django 4.2 on 2023-05-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='companydata',
            name='companyid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='roleid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
