# Generated by Django 4.2 on 2023-06-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_companydata_id_remove_userlist_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='oems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oemid', models.CharField(max_length=255)),
                ('oem_name', models.CharField(max_length=255)),
            ],
        ),
    ]
