# Generated by Django 4.2 on 2023-06-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_marketdata_oem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketdata',
            old_name='oem',
            new_name='oemid',
        ),
    ]
