# Generated by Django 4.2 on 2023-06-15 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_oem_marketdata_oemid'),
    ]

    operations = [
        migrations.CreateModel(
            name='activitylists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oem', models.CharField(choices=[('Nokia', 'Nokia'), ('Ericsson', 'Ericsson')], max_length=255)),
                ('fa_location', models.TextField()),
                ('site_ids', models.TextField()),
                ('lite_site_id', models.TextField()),
                ('three_g_site_id', models.TextField()),
                ('five_g_site_id', models.TextField()),
                ('site_name', models.TextField()),
                ('market', models.TextField()),
                ('address', models.TextField()),
                ('zip_code', models.TextField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('mon_hours', models.TextField()),
                ('tue_hours', models.TextField()),
                ('wed_hours', models.TextField()),
                ('thu_hours', models.TextField()),
                ('fri_hours', models.TextField()),
                ('sat_hours', models.TextField()),
                ('sun_hours', models.TextField()),
                ('key_comments', models.TextField()),
                ('notice_needed', models.TextField()),
                ('notice_comments', models.TextField()),
                ('num_of_carrier', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
                ('pace', models.TextField()),
                ('ptn', models.TextField()),
                ('sow_type', models.TextField(choices=[('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])),
                ('wo_cr_id', models.TextField()),
                ('sow', models.TextField()),
                ('ix_schedule_date', models.DateField()),
                ('nest', models.TextField(choices=[('Yes', 'Yes'), ('No', 'No')])),
                ('mop_start_time', models.TimeField()),
                ('mop_end_time', models.TimeField()),
                ('ix_date_comment', models.TextField()),
                ('equipment_pickup', models.CharField(choices=[('Option 1', 'Option 1'), ('Option 2', 'Option 2')], max_length=255)),
                ('five_g_ix_standalone', models.CharField(choices=[('Option 1', 'Option 1'), ('Option 2', 'Option 2')], max_length=255)),
                ('five_g_ix_schedule_date', models.DateField()),
                ('call_test_date', models.DateField()),
                ('market_state', models.TextField(choices=[('State 1', 'State 1'), ('State 2', 'State 2'), ('State 3', 'State 3')])),
                ('crew_dispatch_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.clientname')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.operator')),
            ],
        ),
    ]
