# Generated by Django 4.2 on 2023-06-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_activitylists'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylists',
            name='Activity',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='activitylists',
            name='Added_By',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylists',
            name='Added_Date',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylists',
            name='Alarm',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylists',
            name='CX_Status',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylists',
            name='County',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylists',
            name='Field_Installation',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylists',
            name='Field_Integration',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylists',
            name='G_IX_date',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylists',
            name='IX_Status',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylists',
            name='Ix_Date',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylists',
            name='Ticket_Number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylists',
            name='Ticket_Status',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylists',
            name='remote_Integration',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
