# Generated by Django 4.2 on 2023-07-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_activitylists_g_ix_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ile_path', models.CharField(max_length=255)),
            ],
        ),
    ]
