# Generated by Django 4.2 on 2023-07-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_filemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='ile_path',
        ),
        migrations.AddField(
            model_name='filemodel',
            name='file',
            field=models.FileField(default=1, upload_to='log_to_excel'),
            preserve_default=False,
        ),
    ]
