# Generated by Django 4.2 on 2023-07-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_delete_excelfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='media/')),
                ('processed_file', models.FileField(upload_to='media/')),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
